### ISSUE TITLE
Learn.co

### ISSUE THREAD

**Issue by onoriodeunu** [learn-co-curriculum/welcome-to-bootcamp-prep#14]
Please talk to about the following topic.
1.HTML AND CSS:Learn the fundamental of web design?
2.Java script:Discover the basics funtional programming?
3.Ruby:Learn ready to ace bootcamp admissions?.

**Comment by onoriodeunu** [comment]
Please talk to about the following topic.
1.HTML AND CSS:Learn the fundamental of web design?
2.Java script:Discover the basics funtional programming?
3.Ruby:Learn ready to ace bootcamp admissions?.

**Comment by Donnadieu** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration
in upcoming releases of this curriculum. 

As always, thanks for contributing! 💙
