### ISSUE TITLE
HTML Fundamentals > HTML >Basics of HTML > Opening and Closing Tags

### ISSUE THREAD

**Issue by SimToor** [learn-co-curriculum/welcome-to-bootcamp-prep#18]
The following sentence is incorrect.  " The paragraph tag tells the browser the text in between it is a paragraph and puts two new lines above and below the text."  

~There is only one line above and one line below.

**Comment by Donnadieu** [comment]
Hi there,

Issues with a lesson in the curriculum should be opened on the appropriate
repository/lab. 

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that others will not encounter the same
problems that you faced.

Thanks for contributing! 💙
