### ISSUE TITLE
We don't explain how to ask a question on the first page.

### ISSUE THREAD

**Issue by cschidlowsky** [learn-co-curriculum/welcome-to-bootcamp-prep#19]
"If you run into any issues or have questions, don’t hesitate to ask! We’re here to help you reach the finish line." --> We should probably note **how** to ask a question here.

**Comment by Donnadieu** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration
in upcoming releases of this curriculum. 

As always, thanks for contributing! 💙
