### ISSUE TITLE
[Feature Request] Reset a learning module from command line. 

### ISSUE THREAD

**Issue by darksheer** [learn-co-curriculum/welcome-to-bootcamp-prep#4]
For students wanting to 'redo' a module, it would be nice to have a reset feature.  Currently I have to delete the forked repo from my account and reclone it. 

I see there is a reset function for the learn script, having something to reset or 'restart' the module would be nice.

**Comment by Donnadieu** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration
in upcoming releases of this curriculum. 

As always, thanks for contributing! 💙
