### ISSUE TITLE
Unclear what banner it is referring to

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/welcome-to-bootcamp-prep#8]
@gj 
The lesson states "We challenge you to read through 2-3 lessons and click the banner below so you can save your progress going forward.", but it is not clear what banner it is referring to.

**Comment by gj** [comment]
Hey @kwebster2 !

I don't work at Flatiron anymore. You can try pinging @jmburges to see who (if anyone) you should highlight going forward.

**Comment by Donnadieu** [comment]
Hi there,

Thank you for your feedback! I believe this has been resolved since this issue was open. I you don't believe this is the case feel free to re-open.

As always, thanks for contributing! 💙
